```yaml id="x8kzzs"
name: Pokemon DB Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Step1
        run: python collect_pokemon_base.py

      - name: Step2
        run: python collect_pokemon_moves.py

      - name: Step3
        run: python collect_move_db.py

      - name: Step4
        run: python collect_pokemon_usage.py

      - name: Step5
        run: python build_db.py

      - name: Step6
        run: python apply_db_output.py
```
